backend:
  repository: "nadineelsayed/proshop-backend"
  tag: "latest"
  containerPort: 5000

frontend:
  repository: "nadineelsayed/proshop-frontend"
  tag: "latest"
  containerPort: 3000

# We use NodePort here because the ALB Ingress will talk to these services
service:
  type: NodePort