apiVersion: apps/v1
kind: Deployment
metadata:
  name: proshop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proshop-frontend
  template:
    metadata:
      labels:
        app: proshop-frontend
    spec:
      containers:
      - name: proshop-frontend
        image: nadineelsayed/proshop-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: proshop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80