apiVersion: v1
kind: ConfigMap
metadata:
  name: proshop-config
data:
  NODE_ENV: "production"
  MONGO_URI: "mongodb+srv://nadeenelsayed12403_db_user:hfxzom3hKKlZztc0@travelmemories.hqxrbvg.mongodb.net/proshop?appName=TravelMemories"
  JWT_SECRET: "abc123"