# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proshop-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proshop-backend
  template:
    metadata:
      labels:
        app: proshop-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          imagePullPolicy: Always
          # This pulls MONGO_URI, JWT_SECRET, and NODE_ENV from your ConfigMap
          envFrom:
            - configMapRef:
                name: proshop-config
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proshop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proshop-frontend
  template:
    metadata:
      labels:
        app: proshop-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"