apiVersion: v1
kind: Service
metadata:
  name: proshop-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: proshop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000