name: Build, Scan, and Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  security-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # STEP 1: GITLEAKS (Fails pipeline if secrets found)
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # STEP 2: BUILD & SCAN (Backend)
      - name: Build Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          load: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proshop-backend:latest

      - name: Trivy Scan Backend (HTML)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/proshop-backend:latest'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-backend-report.html'

      # STEP 3: BUILD & SCAN (Frontend)
      - name: Build Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proshop-frontend:latest

      - name: Trivy Scan Backend (HTML)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/proshop-backend:latest'
          format: 'template'
          template: '@/contrib/html.tpl' 
          output: 'trivy-backend-report.html'

      # STEP 4: UPLOAD REPORTS
      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: trivy-*.html

      # STEP 5: DEPLOY (Will be Green because Terraform is running)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name proshop-eks
          helm upgrade --install proshop ./helm/proshop-chart \
            --set backend.repository=${{ secrets.DOCKERHUB_USERNAME }}/proshop-backend \
            --set backend.tag=latest \
            --set frontend.repository=${{ secrets.DOCKERHUB_USERNAME }}/proshop-frontend \
            --set frontend.tag=latest